### ISSUE TITLE
Install of oci-cli action fails

### ISSUE THREAD

**Issue by dickiesanders** [bytesbay/oci-cli-action#1]
Using the example install step the install fails to find resources dir.

`- name: Install oci-cli
  uses: bytesbay/oci-cli-action@v1.0.1
  with:
    user: "${{ secrets.OCI_USER }}"
    fingerprint: "${{ secrets.OCI_FINGERPRINT }}"
    tenancy: "${{ secrets.OCI_TENANCY }}"
    region: "${{ secrets.OCI_REGION }}"
    api_key: |
      ${{ secrets.OCI_API_KEY }}
    verbose: true`
   

Output:
`Run bytesbay/oci-cli-action@v1.0.1
Creating .oci at /home/runner/.oci
Saving API key to /home/runner/.oci/api_key.pem
Saving config file to /home/runner/.oci/config
Copying oci bin to /usr/local/bin/oci
mv: cannot stat './resources/oci': No such file or directory
Copying oci lib to /lib/oracle-cli
mv: cannot stat './resources/oci-lib/*': No such file or directory
Fixing permissions
/bin/sh: 1: oci: not found
/bin/sh: 1: oci: not found
(node:2052) UnhandledPromiseRejectionWarning: Error: Command failed: sudo mv ./resources/oci /usr/local/bin/oci
mv: cannot stat './resources/oci': No such file or directory
mv: cannot stat './resources/oci-lib/*': No such file or directory
/home/runner/.oci/config
/bin/sh: 1: oci: not found
/bin/sh: 1: oci: not found
`

**Comment by bytesbay** [comment]
Yeah i think i have to revive this package , will do it this night

**Comment by bytesbay** [comment]
Fixed in v1.0.2 release
